### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by jlippold** [aghorler/History-Disabler-for-Chromium#4]
It no longer actively erases history. You have to restart chrome to get history wiped. I'm not sure what changed, chrome or this add-on, but I'm requesting the old functionality re-enabled. 

Thanks :-)

**Comment by aghorler** [comment]
Hi. 

The newest release of the extension should delete history as you close tabs. An update to Chrome has made this a requirement to not break the back/forward navigation functionality.

**Comment by aghorler** [comment]
I've just release version `2.1.0`. This release adds the ability to revert back to the old method of disabling history. 

The release is currently under review by Google.
