### ISSUE TITLE
Recently Closed tabs not cleared

### ISSUE THREAD

**Issue by ThunderMite42** [aghorler/History-Disabler-for-Chromium#5]
Before updating to Chrome 67, this extension would disable the Recently Closed tabs menu (it would always appear empty). I know that the method of deleting history has been changed so as to not interfere with the forward and back arrows, but the new mode doesn't give me the option of disabling Recently Closed (checkbox is disabled when not using Legacy mode). Is a fix for this possible?

**Comment by a8763506128977812212307169331690** [comment]
Hi.

Unfortunately it's not possible to clear recently closed tabs without breaking the back/forward navigation functionality (to clear recently closed tabs in legacy mode the extension clears all browsing history whenever any tab is closed).
